# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField(default=0, editable=False)),
                ('pos_y', models.FloatField(default=0, editable=False)),
                ('rssi', models.FloatField(default=0, editable=False)),
                ('time', models.FloatField(default=0, editable=False)),
                ('imsi', models.CharField(editable=False, max_length=30)),
            ],
        ),
    ]
